Задание 6. Добавлена функциональность регистрации пользователя
gpb-it-factory/ganeev-telegram-bot pull request #8
Opened 2024-06-20 08:49 UTC by Artyom2302

2024-06-20 10:24 UTC, konstantin-kozlovskiy requested changes
Поправить проблемы

2024-06-20 10:24 UTC, konstantin-kozlovskiy commented on src/main/resources/application.yaml
> +  token: 7075026601:AAEpDpSDoyWoyD5tefIKiUYpd3QH1wPfBPA
Почему токен в конфиге? нельзя хранить сенситив информацию в настройках

2024-06-20 15:53 UTC, Artyom2302 commented on src/main/resources/application.yaml
> +  token: 7075026601:AAEpDpSDoyWoyD5tefIKiUYpd3QH1wPfBPA
Исправил, теперь задаю через переменные окружения

2024-06-24 00:29 UTC, konstantin-kozlovskiy approved these changes

2024-06-24 07:12 UTC, merged